# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_Final.cache/wt [current_project]
set_property parent.project_path C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_Final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/modemux.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/logicalmux.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/fulladder.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/arithmeticmuxcin.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/arithmeticmux.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/carry_gen.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/alu_1bit.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/signext15t32.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/regfile.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/pc.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/instruct.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/datememory.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/datamux.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/control.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/alusel_mux.sv
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/32bit_alu.sv
  {C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/FPGA Board/seg_display.sv}
  C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/processor.sv
  {C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/FPGA Board/basys3_wrapper.sv}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/FPGA Board/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/lople/Desktop/_teamNAME-master/TeamName_CPU_Final/TeamName_CPU_final.srcs/FPGA Board/Basys3_Master.xdc}}]


synth_design -top basys3_wrapper -part xc7a35tcpg236-1


write_checkpoint -force -noxdef basys3_wrapper.dcp

catch { report_utilization -file basys3_wrapper_utilization_synth.rpt -pb basys3_wrapper_utilization_synth.pb }
